---
- name: was's port change
  hosts: was
  vars:
          old_port: 8080
          new_port: 60080
  tasks:
          - name: port change
            replace:
                    path: /opt/tomcat/latest/conf/server.xml
                    regexp: '<Connector port="{{old_port}}"'
                    replace: '<Connector port="{{new_port}}"'
            notify:
                    - restart_tomcat
  handlers:
          - name: restart_tomcat
            service:
                    name: tomcat
                    state: restarted
                    enabled: yes
